version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database_development
    networks:
      - app-network

  app:
    image: node:18
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
